### ISSUE TITLE
vendor version?

### ISSUE THREAD

**Issue by pgnd** [dyliano/lineage15.2#2]
I have an Exynos S9+ still running LineageOS's last 15.1-20190517-NIGHTLY-start2lte.

I've read up a bit on your work here, and would like to give it a try.

I have a question about vendor image version.

Your 'newb' README clearly says "Install Vendor image to Vendor partition."

And, the info page says both "Supports final Oreo BSB1 Firmware" & "Use BRI4 vendor".

My current Baseband is: G965FXXU2CSC1 . IIUC, that's "CSC1" vendor.

To upgrade to this latest "15.2" build, do I need to *down*grade my current CSC1 to the earlier BRI4 vendor?

**Comment by WesleyVanNeck** [comment]
BSB1
